### ISSUE TITLE
Switch buildsystem to CMake from qmake

### ISSUE THREAD

**Issue by JamiKettunen** [cutie-shell/qml-module-cutie#3]
~~QMake is [deprecated in Qt 6 and "is going to vanish anytime soon"](https://www.qt.io/blog/qt-6-build-system) so we might as well be prepared for the future :)~~

Nvm that only affects building Qt itself from source; considering the default is CMake and Qt itself is still built with CMake starting with Qt 6 it would be a nice enhancement to start moving away from `qmake` eventually.

**Comment by erikinkinen** [comment]
This is definitely something to consider. At least, I, personally, like the idea.

If @xyn or @Vin4ter have no objections against this, I shall switch in the near future. Also, MRs would be welcome because the whole project need a lot of work in everything.

Thank you for bringing this up!

**Comment by arpio23** [comment]
This is now completed with qt6 porting.

**Comment by erikinkinen** [comment]
If anyone needs to know, commit de81318f7a27eea7e203c789fdd1dc88b314dd39 was the one where CMake was taken in use.
